export const FETCHUSERS = "FETCHUSERS";
export const FETCHUSERSSUCCESS = "FETCHUSERSSUCCESS";
export const FETCHUSERSERROR = "FETCHUSERSERROR";
export const TOGGLESUBSCRIPTION = "TOGGLESUBSCRIPTION";
export const ADDSTORE = "ADDSTORE";
